{{- if and .Values.prometheus.enabled .Values.prometheus.authentication.enabled .Values.prometheus.authentication.username .Values.prometheus.authentication.password (not .Values.prometheus.authentication.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nodereaper.fullname" . }}-prometheus
  namespace: {{ include "nodereaper.namespace" . }}
  labels:
    {{- include "nodereaper.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.prometheus.authentication.username | b64enc }}
  password: {{ .Values.prometheus.authentication.password | b64enc }}
{{- end }}
